# ETAPA 1: Compilar Despachos
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app
COPY despachos/pom.xml .
COPY despachos/src ./src
RUN mvn clean package -DskipTests

# ETAPA 2: Imagen final ligera
FROM eclipse-temurin:17-jre
RUN addgroup --system --gid 1001 appgroup && adduser --system --uid 1001 --gid 1001 appuser
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
RUN chown -R appuser:appgroup /app
USER appuser

EXPOSE 8081
CMD ["java", "-jar", "app.jar"]